yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('Адрес группы', unique=True)
    description = models.TextField('Описание группы')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста')
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Название группы'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментируемый пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField('Текст комментария')
    created = models.DateTimeField('Дата публикации', auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь, который подписывается'
    )
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор, на которого подписываются'
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Внесите текст вашего поста')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utilis import get_page_obj


@cache_page(20, key_prefix="index_page")
def index(request):
    page_obj = get_page_obj(
        Post.objects.select_related('author', 'group').all(), request)
    context = {'page_obj': page_obj}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = get_page_obj(group.posts.all(), request)
    context = {'page_obj': page_obj, 'group': group}
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = User.objects.get(username=username)
    page_obj = get_page_obj(Post.objects.filter(author=author), request)
    following = (request.user.is_authenticated and Follow.objects.filter(
                 author=author, user=request.user).exists())
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        context = {'form': form, 'is_edit': False}
        post.save()
        return redirect('posts:profile', post.author)
    context = {'form': form, 'is_edit': False}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {'form': form, 'is_edit': True}
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    page_obj = get_page_obj(
        Post.objects.filter(author__following__user=request.user), request)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        if not Follow.objects.filter(
                user=request.user, author=author).exists():
            Follow.objects.create(user=request.user, author=author)
            return redirect('posts:profile', username=username)
        Follow.objects.get(user=request.user, author=author)
        return redirect('posts:profile', username=username)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {% if is_edit %}Редактировать запись{% else %}Новый пост{% endif %}{% endblock %}
	   
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}Редактировать запись{% else %}Новый пост{% endif %}          
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% if form.errors %}
              {% for field in form %} 
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data" action="{% if is_edit %} {{ request.get_full_path }} {% else %} {% url 'posts:post_create' %} {% endif %}">
              {% csrf_token %} 
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
                  <small 
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                    >
                    {{ field.help_text|safe }}
                  </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4"> 
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}Добавить{% else %}Сохранить{% endif %}
                </button>
              </div>  
            </form> 
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}    

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Посты Ваших любимых авторов{% endblock %}

<body>
  {% block content %}
    <div class="container">
      <h1>Последние посты Ваших любимых авторов</h1>
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'posts/includes/post_order.html' %}
      {% endfor %}  
      {% include 'posts/includes/paginator.html' %} 
    </div>      
  {% endblock %}
</body>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Записи сообщества {{ group.title }}{% endblock %}

<body>
  {% block content %}
    <div class="container">
      <h1>{{ group.title }}</h1>
       <p>{{ group.description }}</p>
       {% for post in page_obj %}
          {% include 'posts/includes/post_order.html' %}
       {% endfor %}  
       {% include 'posts/includes/paginator.html' %}
    </div>
  {% endblock %}
</body>

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Последние обновления на сайте{% endblock %}

<body>
  {% block content %}
    <div class="container">
      <h1>Последние обновления на сайте</h1>
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'posts/includes/post_order.html' %}
      {% endfor %} 
      {% include 'posts/includes/paginator.html' %} 
    </div>      
  {% endblock %}
</body>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load user_filters %}


{% block title %}Пост: {{post.text|truncatechars:30}} {% endblock %}

<body>
  {% block content %}
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>  
            <li class="list-group-item">
              Группа:
              {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group.title }}
              </a> 
              {% endif %} 
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{post.author.authors.count}}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
          
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text | linebreaksbr }}
          </p>
          {% if user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            Редактировать пост
          </a>
          {% endif %}
        
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
        {% endif %}
      
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endfor %} 
        </article>
      </div>
    </div>
  {% endblock %}
</body>

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}

<body>
  {% block content %}
    <div class="container py-5"> 
      <div class="mb-5">      
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{author.posts.count}} </h3>
        {% if user.is_authenticated %}
          {% if user != author %}
            {% if following %}
              <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button"
              >
                Отписаться
              </a>
            {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
                Подписаться
              </a>
            {% endif %}
          {% endif %}
        {% endif %}
      </div>
      {% for post in page_obj %}
        {% include 'posts/includes/post_order.html' %}
      {% endfor %} 
      {% include 'posts/includes/paginator.html' %} 
    </div>          
  {% endblock %}
</body>